BACKUP DATABASE [SEDC] 
TO  DISK = N'C:\SEDC_test_Backup_20210628\SEDC_bck_20210628' 
WITH  COPY_ONLY, NOFORMAT, NOINIT,  NAME = N'SEDC-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO


USE [master]
RESTORE DATABASE [SEDC_2] FROM  
DISK = N'C:\SEDC_test_Backup_20210628\SEDC_bck_Full' WITH  FILE = 1,  
MOVE N'SEDC' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SEDC_2',  
MOVE N'SEDC_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SEDC_2_log.ldf',  NOUNLOAD,  STATS = 5

GO

